"""Session 19.5 step 7: the report. Figures read from emitted CSVs under 9.12."""
from __future__ import annotations
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "session-19_5"


def rd(n):
    return list(csv.DictReader(open(OUT / n)))


src, qc = rd("ladder-source.csv"), rd("qqq-control.csv")
dec, ca = rd("ladder-decomposition.csv"), rd("construction-audit.csv")
lo, ws = rd("lo-control.csv"), rd("window-strip.csv")
ce, dsw = rd("coverage-early.csv"), rd("defect-sweep.csv")
iv = rd("input-verification.csv")


def g(rows, table, item, field="value"):
    for r in rows:
        if r["table"] == table and r["item"] == item:
            return r[field]
    return ""


def f(rows, table, item, field="value"):
    v = g(rows, table, item, field)
    return float(v) if v not in ("", None) else float("nan")


L = []
A = L.append
A("# Session 19.5 report")
A("")
A("Run 2026-08-19. Ladder construction audit then window strip. No holdout was")
A("executed and the 2021-08-01 boundary is untouched. No grid was re-executed and no")
A("grid point was adopted or promoted. The primary window remains 2011-10-04. No")
A("strategy parameter, threshold, instrument, weight, sleeve budget, cost model, cap")
A("level, premium, NAV, or window boundary changed, and no construction defect was")
A("repaired here.")
A("")
A("Every figure below is read from an emitted CSV in `outputs/session-19_5/` under 9.12.")
A("")
A("## Opening three")
A("")
A(f"**The canonical positive control passes.** Rebuilt from the frozen inputs rather")
A(f"than read from the deleted grid, the canonical specification returns")
A(f"{f(qc,'positive_control','ann_return'):.6f} annualised and")
A(f"{f(qc,'positive_control','sharpe_lo'):.6f} Lo-corrected Sharpe over")
A(f"{int(f(qc,'positive_control','n_sessions'))} sessions, against targets 0.521845 and")
A(f"1.381701 at gaps of {f(qc,'positive_control','ann_return','abs_gap'):.2e} and")
A(f"{f(qc,'positive_control','sharpe_lo','abs_gap'):.2e} inside a 5e-07 tolerance stated")
A("before comparing. All 339 manifested frozen inputs verify with zero mismatches.")
A("")
A(f"**The QQQ row does not deviate.** Rebuilt with the ladder's own entry index and")
A(f"start date, buy-and-hold QQQ reproduces the emitted ladder row to a worst gap of")
A(f"{f(qc,'qqq_vs_ladder','worst_gap'):.2e} against a 5e-05 tolerance stated before")
A("comparing. The motivating arithmetic argument is not borne out as an arithmetic")
A("error in the row.")
A("")
A(f"**No ladder row is a costless scaling.** The construction audit verdict is that")
A(f"the levered rows hold the live fund ticker rather than a scaling of QQQ, and the")
A("decisive check confirms it on the sharpest available discriminator.")
A("")
A("## Step 0, the ladder artifact")
A("")
A(f"The twelve-row ladder is `outputs/session-15/metrics-full.csv`, written by session")
A(f"15, carrying {int(f(src,'artifact','n_rows_file'))} rows across")
A(f"{int(f(src,'artifact','n_columns'))} columns of which")
A(f"{int(f(src,'artifact','n_rows_designated_cell'))} sit in the designated cell.")
A(f"Twelve rows exist. Session 14's `ladder.csv` carries fourteen lines including the")
A("intraday-only and overnight-only hold universes, which the twelve-row ladder drops.")
A("")
A("All six prose figures match the CSV at the three decimals the prose carries, with")
A(f"{int(f(src,'prose_check','disagreements'))} disagreements.")
A("")
A("**Every ladder row is on the superseded window.** The ladder's STRATEGY row reads")
A(f"{f(src,'boundary','ladder_strategy_sharpe_lo'):.4f} over")
A(f"{int(f(src,'boundary','ladder_strategy_n_sessions'))} sessions, which is the")
A("pre-correction 2011-10-03 start. Register 7.14a superseded that with 1.3817 over")
A("2472 sessions on the 2011-10-04 start. Session 15 ran before that correction and")
A("`s14_common.PRIMARY_START` still defaults to 2011-10-03, so every ladder row carries")
A("the superseded boundary. This is documentation of a known correction not yet")
A("propagated, rather than a new defect.")
A("")
A("**Romano-Wolf, with the sign now established.** One of eleven one-sided comparisons")
A("sits below 0.05, being the equal-weight universe at 0.033 with a mean daily")
A(f"difference of {f(src,'romano_wolf','strategy_minus_equal_weight_universe','mean_daily_diff'):+.6f}")
A("and a t of")
A(f"{f(src,'romano_wolf','strategy_minus_equal_weight_universe','t_stat'):+.3f}, so the")
A("**strategy is above** the equal-weight universe. Buy-and-hold QQQ follows at 0.052,")
A("also with the strategy above. The strategy sits below buy-and-hold TQQQ, both S2 and")
A("S3 standalone, and long-legs-only, none of which reaches 0.05.")
A("")
A("## Step 1, the QQQ row")
A("")
A("Over the corrected primary window from the frozen input.")
A("")
A("| quantity | value |")
A("|---|---|")
A(f"| annualised return | {f(qc,'qqq','corrected_2011_10_04','ann_return'):.6f} |")
A(f"| annualised volatility | {f(qc,'qqq','corrected_2011_10_04','ann_vol'):.6f} |")
A(f"| mean risk-free rate over the window | {f(qc,'qqq','corrected_2011_10_04','mean_rf_ann'):.6f} |")
A(f"| naive Sharpe | {f(qc,'qqq','corrected_2011_10_04','sharpe_naive'):.6f} |")
A(f"| Lo-corrected Sharpe | {f(qc,'qqq','corrected_2011_10_04','sharpe_lo'):.6f} |")
A(f"| implied Lo factor | {f(qc,'qqq','corrected_2011_10_04','lo_factor'):.6f} |")
A(f"| first-order daily autocorrelation | {f(qc,'qqq','corrected_2011_10_04','rho1'):+.6f} |")
A(f"| lag count in the correction | {int(f(qc,'qqq','corrected_2011_10_04','lag_count'))} |")
A(f"| weighted autocorrelation sum | {f(qc,'qqq','corrected_2011_10_04','acf_sum'):.3f} |")
A(f"| sessions | {int(f(qc,'qqq','corrected_2011_10_04','n_sessions'))} |")
A("")
A("The motivating arithmetic put QQQ's naive Sharpe near 1.25 and the measurement puts")
A(f"it at {f(qc,'qqq','corrected_2011_10_04','sharpe_naive'):.4f}, so the naive figure is")
A("lower than the argument assumed rather than higher.")
A("")
A("**External verification is pending.** The only QQQ total-return path in this")
A("repository is the frozen input the ladder itself used, so no independent series")
A("exists offline and no network fetch was attempted inside this session.")
A("")
A("## The Lo correction, measured against its own null")
A("")
A("`bt.lo_sharpe` sums 251 weighted sample autocorrelations estimated from 2472")
A("observations. The question the motivation raises is whether a factor of that size is")
A("supported. It is answered by a control rather than by argument.")
A("")
A(f"The null is {int(f(lo,'lo_control','draws'))} independent permutations of the same")
A(f"excess returns at seed {int(f(lo,'lo_control','seed'))} fixed before drawing, which")
A("preserves the marginal distribution and destroys serial dependence entirely.")
A("")
A("| quantity | observed | null mean | null sd | null 5th | null 95th |")
A("|---|---|---|---|---|---|")
A(f"| weighted autocorrelation sum | {f(lo,'lo_control','observed_acf_sum'):.3f} | "
  f"{f(lo,'lo_control','null_acf_sum_mean'):.3f} | {f(lo,'lo_control','null_acf_sum_sd'):.3f} | | |")
A(f"| implied Lo factor | {f(lo,'lo_control','observed_lo_factor'):.4f} | "
  f"{f(lo,'lo_control','null_lo_factor_mean'):.4f} | {f(lo,'lo_control','null_lo_factor_sd'):.4f} | "
  f"{f(lo,'lo_control','null_lo_factor_p05'):.4f} | {f(lo,'lo_control','null_lo_factor_p95'):.4f} |")
A("")
A(f"The observed sum sits {abs(f(lo,'lo_control','observed_z_against_null')):.3f} standard")
A("deviations from a null in which there is no autocorrelation at all, and a series with")
A("no autocorrelation still produces a mean Lo factor of")
A(f"{f(lo,'lo_control','null_lo_factor_mean'):.4f} reaching")
A(f"{f(lo,'lo_control','null_lo_factor_p95'):.4f} at the 95th percentile. The null mean is")
A("not one because each sample autocorrelation carries a small-sample bias of order")
A("minus one over n and 251 of them are summed with weights up to 251.")
A("")
A("Stated as measured, the Lo-corrected Sharpe as implemented carries a scale factor")
A("whose sampling dispersion is of the same order as the difference between ladder rows.")
A("")
A("## Step 2, ladder decomposition")
A("")
A("Every one of the twelve rows reproduces from the frozen inputs, worst gap")
A(f"{f(dec,'ranking','worst_reproduction_gap'):.2e} against the 5e-05 tolerance.")
A("")
A("| line | naive | rank | Lo | rank | Lo factor | rho1 | turnover |")
A("|---|---|---|---|---|---|---|---|")
drows = [r for r in dec if r["table"] == "decomposition"]
for r in sorted(drows, key=lambda r: int(r["rank_lo"])):
    A(f"| {r['item']} | {float(r['sharpe_naive']):.4f} | {r['rank_naive']} | "
      f"{float(r['sharpe_lo']):.4f} | {r['rank_lo']} | {float(r['lo_factor']):.4f} | "
      f"{float(r['rho1']):+.4f} | {float(r['ann_turnover']):.2f} |")
A("")
A(f"**{int(f(dec,'ranking','rows_with_rank_change'))} of twelve rows change rank between")
A("the two metrics.** The strategy holds rank")
A(f"{int(f(dec,'ranking','strategy_rank_naive'))} under the naive Sharpe and rank")
A(f"{int(f(dec,'ranking','strategy_rank_lo'))} under the Lo-corrected Sharpe, so its own")
A("position is unchanged while the ordering around it is not.")
A("")
A("The three rows the motivation identified as suspiciously close, being buy-and-hold")
A("TQQQ, buy-and-hold QQQ, and matched-exposure levered QQQ, span")
A(f"{f(dec,'trio_spread','trio_spread_sharpe_lo'):.4f} on the Lo-corrected Sharpe and")
A(f"{f(dec,'trio_spread','trio_spread_sharpe_naive'):.4f} on the naive Sharpe, a factor of")
A(f"{f(dec,'trio_spread','trio_spread_ratio'):.2f} wider.")
A("Their Lo factors are 1.5718, 1.5322 and 1.5723. The convergence is produced by the")
A("correction rather than by the construction.")
A("")
A("## Step 3, construction audit")
A("")
A("On the realized arm `bt.load_arm_panel` takes every levered ticker from")
A("`_frozen_frame`, being the frozen fund parquet, so the series is the live fund's own")
A("history with its real daily reset, financing and expense already embedded by the")
A("issuer. On the synthetic arm the same tickers come from `_synthetic_frame`, being the")
A("reconstruction. The designated cell is the realized arm.")
A("")
A("Financing applies to the reconstructions only. The rate source is the frozen DTB3")
A("accrued at rate over 360 per calendar day between sessions under the 5.5a convention,")
A("the spread is `config.FINANCING_SPREAD_BP` over that reference for multiples above")
A("one with a haircut for inverse funds and k equal to zero for the volatility funds")
A("under 2.15, and the reset compounds daily with a daily close rebalance.")
A("")
A("**Decisive check.** Tolerance 5e-03 on annualised Sharpe, stated before comparing.")
A("")
A("| series | annualised return | annualised volatility | naive Sharpe |")
A("|---|---|---|---|")
for k, nm in (("costless_3x_QQQ", "costless 3x QQQ, daily compounded, no financing"),
              ("live_TQQQ", "live TQQQ"),
              ("ladder_buy_hold_TQQQ", "ladder buy-and-hold TQQQ row")):
    A(f"| {nm} | {f(ca,'decisive_check',k,'ann_return'):.6f} | "
      f"{f(ca,'decisive_check',k,'ann_vol'):.6f} | "
      f"{f(ca,'decisive_check',k,'sharpe_naive'):.6f} |")
A("")
A(f"The ladder row sits {f(ca,'decisive_check','gap_vs_costless'):.6f} from the costless")
A(f"construction and {f(ca,'decisive_check','gap_vs_live'):.6f} from the live fund on")
A("naive Sharpe, so neither is inside the tolerance and the Sharpe does not")
A("discriminate. Annualised volatility does, being untouched by the risk-free")
A("subtraction and by the account's cash accrual. The row sits")
A(f"{f(ca,'decisive_check','vol_gap_vs_live'):.6f} from the live fund and")
A(f"{f(ca,'decisive_check','vol_gap_vs_costless'):.6f} from the costless construction, a")
A("factor of nine closer to the live fund.")
A("")
A(f"**Verdict: the row is not a costless scaling**, recorded as")
A(f"`row_is_costless_scaling` = {int(f(ca,'decisive_check','row_is_costless_scaling'))}.")
A("")
A("## Gate")
A("")
A("The gate clears on both of its conditions, since no levered or inverse row is a")
A("costless scaling and the QQQ row does not deviate beyond tolerance. Step 4 ran.")
A("")
A("Two findings the gate does not cover are recorded rather than treated as passing,")
A("being the superseded boundary on every ladder row and the sampling behaviour of the")
A("Lo correction.")
A("")
A("## Step 4, the window strip")
A("")
A("A post-hoc sensitivity under 9.10. The primary window remains 2011-10-04. The")
A("positive control at the canonical start reproduces the canonical to")
A(f"{f(ws,'strip_positive_control','ann_return','abs_gap'):.2e} and")
A(f"{f(ws,'strip_positive_control','sharpe_lo','abs_gap'):.2e}.")
A("")
A("| start | date | sessions | annualised | naive | Lo | rank naive | rank Lo | realized-available share |")
A("|---|---|---|---|---|---|---|---|---|")
for r in [x for x in ws if x["table"] == "strip"]:
    A(f"| {r['item']} | {r['start']} | {int(float(r['n_sessions']))} | "
      f"{float(r['ann_return']):.4f} | {float(r['sharpe_naive']):.4f} | "
      f"{float(r['sharpe_lo']):.4f} | {r['strategy_rank_naive']} | "
      f"{r['strategy_rank_lo']} | "
      f"{float(r['share_sessions_all_realized_available']):.3f} |")
A("")
A("**The strategy's rank is not stable across start dates.** It spans")
A(f"{g(ws,'rank_stability','naive_range','note')} under the naive Sharpe and")
A(f"{g(ws,'rank_stability','lo_range','note')} under the Lo-corrected Sharpe. The")
A("canonical start returns the lowest rank of any start date tested under both metrics.")
A("Reported as measured, with no interpretation and no change to the primary window.")
A("")
A("## Step 5, coverage at the earliest start")
A("")
A(f"**The earliest date at which all sleeves reach full composition on the synthetic")
A(f"panel is {g(ce,'early_start','full_composition_date','note')}**, not 2007. It is bound")
A(f"by {g(ce,'early_start','binding_ticker','note')} first appearing")
A(f"{g(ce,'early_start','binding_ticker_first_session','note')} plus")
A(f"{int(f(ce,'early_start','warmup_sessions'))} warmup sessions. That date is **later**")
A("than the canonical 2011-10-04, so the synthetic panel supports no genuinely early")
A("full-composition arm and the strip has no arm that reaches back before the canonical")
A("window.")
A("")
A(f"Over the {int(f(ce,'coverage_early','n_sessions'))} sessions from that start,")
A(f"{f(ce,'coverage_early','share_all_realized_available'):.4f} of sessions have every")
A(f"sleeve-held ticker available on the realized panel and")
A(f"{f(ce,'coverage_early','share_requiring_synthetic'):.4f} do not, so a start there is")
A("confounded with panel source since the panel differs alongside the window. The")
A("confound is disclosed rather than resolved.")
A("")
A("**Register tension, recorded and left open.** Register 7.14b fixed the early-window")
A("reporting form as coverage tables and availability timelines with no return figure at")
A("any prominence. Step 4 emits return figures at the early start as a diagnostic, which")
A("is in tension with that form. Whether any early-start figure enters the paper is a")
A("register decision this session does not make and does not pre-empt.")
A("")
A("## Step 6, defect class sweep under 9.13")
A("")
A("Run regardless of the gate. Step 3 found no construction defect, so there is no")
A("defect class to sweep. The sweep instead records the construction of all fourteen")
A("levered and inverse instruments the strategy trades, being the leveraged longs, the")
A("inverse funds, and the two volatility ETPs. Each takes the frozen fund parquet on the")
A("realized arm and the reconstruction on the synthetic arm, and the two arms are the")
A("registered pair rather than a defect.")
A("")
A(f"**The canonical result does not depend on any instrument carrying the defect**,")
A(f"recorded as `canonical_depends_on_defect` = "
  f"{int(f(dsw,'sweep','canonical_depends_on_defect'))}, since the canonical runs on the")
A("realized arm where every levered and inverse instrument is the live fund's own frozen")
A("history. Nothing was repaired.")
A("")
A("## Findings and the class of change each would need")
A("")
A("| finding | class |")
A("|---|---|")
A("| every ladder row carries the superseded 2011-10-03 boundary | correctness repair, owned by session 20 step 5 |")
A("| the Lo factor's sampling dispersion is of the same order as the gaps between ladder rows | register decision on whether 8.2 keeps the Lo-corrected Sharpe as headline |")
A("| eight of twelve rows change rank between the naive and Lo-corrected metrics | documentation |")
A("| the strategy's rank varies across start dates and is lowest at the canonical start | documentation, the primary window is unchanged |")
A("| no full-composition start earlier than canonical exists on the synthetic panel | documentation |")
A("| the 7.14b reporting form is in tension with emitting early-start return figures | register decision |")
A("| no construction defect in any levered or inverse line | nothing to act on |")
A("| external QQQ verification pending, no independent offline series | specification change if an independent source is added |")
A("")
A("No recommendation is made on any of these.")
A("")
A("## Resources")
A("")
A(f"A memory ceiling of {f(ca,'resources','memory_ceiling_gb'):.1f} GB was stated before")
A(f"running. Peak observed was {f(ca,'resources','peak_rss_gb'):.3f} GB across steps 1 to")
A(f"3 and {f(ws,'resources','peak_rss_gb'):.3f} GB across steps 4 to 6, both far below the")
A("ceiling as single-specification runs were expected to be.")
A("")
A("| step | seconds |")
A("|---|---|")
for it, lbl in (("seconds_build_env", "environment build"),
                ("seconds_step1_canonical", "step 1 positive control"),
                ("seconds_step1_qqq", "step 1 QQQ"),
                ("seconds_step2", "step 2 decomposition"),
                ("seconds_step3", "step 3 construction audit"),
                ("seconds_lo_control", "Lo sampling control")):
    v = g(ca, "resources", it)
    if v:
        A(f"| {lbl} | {float(v):.1f} |")
A(f"| steps 4 to 6 | {f(ws,'resources','seconds_total'):.1f} |")
A("")
A("## Stop condition")
A("")
A("Halted after step 8. No holdout executed and the 2021-08-01 boundary untouched. No")
A("grid re-executed and no grid point adopted or promoted. The primary window remains")
A("2011-10-04. No construction defect repaired. One commit.")
A("")
(OUT / "REPORT.md").write_text("\n".join(L) + "\n")
print(f"wrote {OUT/'REPORT.md'}")
