from __future__ import annotations
import csv
from pathlib import Path
ROOT=Path("/Users/GualyCr/Downloads/tactical-allocation"); OUT=ROOT/"outputs/session-20"
def rd(n): return list(csv.DictReader(open(OUT/n)))
lq,dsc,ac,ax,en,ja,gn = (rd("lo-q-sweep.csv"),rd("deflated-sharpe-corrected.csv"),
    rd("axis-census.csv"),rd("axes-sourced.csv"),rd("effective-n.csv"),
    rd("jan2013-attribution.csv"),rd("degradation-null-corrected.csv"))
def g(rs,t,i,f="value",key="item"):
    for r in rs:
        if r["table"]==t and r.get(key)==i: return r.get(f)
    return ""
def fl(rs,t,i,f="value",key="item"):
    v=g(rs,t,i,f,key); return float(v) if v not in ("",None) else float("nan")
L=[];A=L.append
A("# Session 20 report, phases D through G")
A("")
A("`REPORT.md` covers phases A through C. This document covers D through G, resumed")
A("after phase C's gate tripped. **Phase C is recorded as failed.** The gate condition")
A("was that both randomization nulls clear p below 0.001 on the designated cell, and")
A("the timing-shuffle null on annualised return did not. D through G ran on the")
A("corrected boundary regardless, since the boundary repair itself succeeded.")
A("")
A("The holdout boundary is untouched, no grid was re-executed, and no grid point was")
A("adopted. Every figure is read from an emitted CSV in `outputs/session-20/`.")
A("")
A("## The headline of this half")
A("")
A(f"**The 121,500 specifications are not 121,500 independent trials.** Across the")
A(f"pre-registered 2,000-specification subsample the correlation spectrum puts")
A(f"{fl(en,'effective_n','top_eigenvalue_share','in_N','axis')*100:.1f} percent of total")
A("variance in the first principal component, and the effective count is")
A(f"{fl(en,'effective_n','participation_ratio','in_N','axis'):.2f} under the participation")
A(f"ratio, {int(fl(en,'effective_n','variance_threshold_95','in_N','axis'))} under a 95 percent")
A(f"variance threshold, and {fl(en,'effective_n','spectral_entropy','in_N','axis'):.2f} under")
A("spectral entropy. The canonical's deflated Sharpe moves from")
_pre=float([r['sharpe_lo'] for r in en if r['table']=='effective_n_deflated'
            and r['axis']=='preregistered_121500' and r['arm']=='canonical'][0])
_pr=float([r['sharpe_lo'] for r in en if r['table']=='effective_n_deflated'
           and r['axis']=='participation_ratio' and r['arm']=='canonical'][0])
A(f"{_pre:.6f} at the pre-registered N to {_pr:.6f} at the participation-ratio")
A("count. Recorded as a disclosed post-hoc sensitivity under 9.10 with the primary")
A("remaining N equal to 121,500.")
A("")
A("## D1, the Lo lag count")
A("")
A("`lo_sharpe(excess, q=252)` is a Python default parameter, absent from `config.py`,")
A("absent from every curve axis, and never swept until now.")
A("")
A("| q | strategy Lo Sharpe | strategy rank |")
A("|---|---|---|")
for q in (1,5,21,63,126,252):
    v=[r["value"] for r in lq if r["table"]=="q_sweep" and r["line"]=="STRATEGY" and r["q"]==str(q)][0]
    rk=[r["value"] for r in lq if r["table"]=="q_rank" and r["line"]=="STRATEGY" and r["q"]==str(q)][0]
    A(f"| {q} | {float(v):.4f} | {int(float(rk))} |")
A("")
A(f"The strategy's rank spans {g(lq,'q_summary','STRATEGY_rank_range','note','line')}")
A(f"across the sweep, and **{int(fl(lq,'q_summary','rows_changing_rank_across_q','value','line'))}")
A("of twelve rows change rank**. q equal to 1 is the naive Sharpe limit.")
A("")
A("### Every row against its own no-autocorrelation null")
A("")
A(f"{int(fl(lq,'lo_null_meta','draws','value','line'))} permutations per row at seed")
A(f"{int(fl(lq,'lo_null_meta','seed','value','line'))} fixed before drawing.")
A("")
A("| line | observed factor | null 5th | null 95th | inside own null |")
A("|---|---|---|---|---|")
for r in lq:
    if r["table"]=="lo_null":
        A(f"| {r['line']} | {float(r['value']):.4f} | {float(r['null_p05']):.4f} | "
          f"{float(r['null_p95']):.4f} | {'yes' if r['inside_own_null']=='1' else 'no'} |")
A("")
A(f"**{int(fl(lq,'lo_null_meta','rows_inside_own_null','value','line'))} of twelve rows")
A("fall inside their own null**, meaning their Lo factor is indistinguishable from what")
A("a series with no autocorrelation produces at this sample length. The three that fall")
A("outside are exactly the three rows that outrank the strategy on the Lo-corrected")
A("Sharpe, being buy-and-hold TQQQ, buy-and-hold QQQ, and matched-exposure levered QQQ.")
A("The strategy's own factor is inside its null.")
A("")
A(f"The Lo variance estimate turns non-positive at a weighted autocorrelation sum of")
A(f"{fl(lq,'lo_null_meta','negative_variance_threshold','value','line'):.1f}. Every row")
A("sits above it, with the three outside-null rows closest at 1.16 to 1.23 null standard")
A("deviations and the rest between 1.60 and 2.98.")
A("")
A("## D2, the deflated Sharpe corrected to N equal to 121,500")
A("")
A(f"{g(dsc,'grounds','correction_class','note')}")
A("")
A("| point | metric | N=121,500 | N=364,500 superseded |")
A("|---|---|---|---|")
for wh in ("canonical","in_sample_best"):
    a=[r["value"] for r in dsc if r["table"]=="corrected_deflated_sharpe" and r["item"]==wh
       and r["sharpe_metric"]=="sharpe_naive" and r["metric"]=="deflated_sharpe_N_121500"][0]
    b=[r["value"] for r in dsc if r["table"]=="corrected_deflated_sharpe" and r["item"]==wh
       and r["sharpe_metric"]=="sharpe_naive" and r["metric"]=="deflated_sharpe_N_364500"][0]
    A(f"| {wh} | naive Sharpe | {float(a):.6f} | {float(b):.6f} |")
A("")
A(f"The propagation sweep found {int(fl(dsc,'propagation_summary','sites_found'))} sites")
A(f"carrying the figure, of which {int(fl(dsc,'propagation_summary','sites_designating_N'))}")
A("designate N and require correction. The remainder state the size of the enumerated")
A("space, which remains true, including `MANIFEST.json`'s `grid.n_enumerated` field.")
A("")
A("## D3, the degradation slope")
A("")
A(f"**Status {g(dsc,'slope_disposition','status')}.** {g(dsc,'slope_disposition','status','note')}.")
A(f"The corrected value carried forward is {g(dsc,'slope_disposition','corrected_n_is_slope')}")
A(f"against the emitted {g(dsc,'slope_disposition','as_emitted_slope')}, since")
A("the phase B1 re-emission halted on the memory gate. The statistic is a candidate for")
A("removal from the paper and no recommendation is made on whether to remove it.")
A("")
A(f"Session 19.6's PBO null is retained as an **estimator control** rather than as a")
A(f"test. A harness fed selection driven purely by idiosyncratic noise returned a PBO of")
A(f"{float(g(dsc,'estimator_control','pbo_null_mean')):.6f} against the observed")
A(f"{float(g(dsc,'estimator_control','pbo_observed')):.6f}, which is a validation the")
A("observed figure never carried on its own.")
A("")
A("## E1, the axis census")
A("")
A(f"**The authoritative count of searched degrees of freedom is")
A(f"{int(fl(ac,'authoritative_count','searched_degrees_of_freedom','in_N','axis'))}**, being the")
A("nine grid axes. The curve axes are reported sensitivities rather than a search over")
A("which a maximum was taken, so they do not enter N.")
A("")
A("| discrepancy | resolution |")
A("|---|---|")
for r in ac:
    if r["table"]=="discrepancy":
        A(f"| {r['axis']} | {r['note']} |")
A(f"| tier_two_offset | {g(ac,'census','tier_two_offset','note','axis')} |")
A("")
A("## E2, sourcing the three open axes")
A("")
A("| arm | annualised | naive Sharpe | Lo Sharpe |")
A("|---|---|---|---|")
for r in ax:
    if r["table"]=="axis_arm":
        nm = r["axis"] if r["axis"]=="canonical" else f"{r['axis']} {r['arm']}"
        A(f"| {nm} | {float(r['ann_return']):.6f} | {float(r['sharpe_naive']):.6f} | "
          f"{float(r['sharpe_lo']):.6f} |")
A("")
A("**Two of the three cannot be sourced by measurement.**")
A("")
for r in ax:
    if r["table"]=="axis_unsourceable":
        A(f"- **{r['axis']}**, {r['status']}. {r['note']}")
A("")
A("The sizing-mode finding is a new instance of the phase B3 hardcoded-literal class and")
A("was not known before this phase.")
A("")
A("## E3, effective N")
A("")
A(f"The subsample carries {int(fl(en,'effective_n','subsample_size','in_N','axis'))} series and")
A("the canonical sits inside it, reproducing session 19 step 3's positive control.")
A("")
A("| definition | effective count | expected maximum Sharpe | canonical deflated Sharpe |")
A("|---|---|---|---|")
for nm in ("participation_ratio","spectral_entropy","variance_threshold_95","preregistered_121500"):
    rr=[r for r in en if r["table"]=="effective_n_deflated" and r["axis"]==nm and r["arm"]=="canonical"][0]
    A(f"| {nm} | {float(rr['in_N']):.2f} | {float(rr['ann_return']):.4f} | "
      f"{float(rr['sharpe_lo']):.6f} |")
A("")
A(f"The canonical's naive Sharpe is {float([r['sharpe_naive'] for r in en if r['table']=='effective_n_deflated' and r['arm']=='canonical'][0]):.4f}, which sits")
A("above the expected maximum at every effective count and below it at the")
A("pre-registered N. **Primary remains N equal to 121,500.**")
A("")
A("## F, the January 2013 event")
A("")
A(f"The span runs 2013-01-02 to 2013-01-22, {int(fl(ja,'span','n_sessions','weight'))}")
A(f"sessions, cumulative {fl(ja,'span','cumulative_return','contribution'):.6f}.")
A("")
A("| sleeve | arithmetic contribution |")
A("|---|---|")
for r in ja:
    if r["table"]=="sleeve_attribution":
        A(f"| {r['item']} | {float(r['contribution']):+.6f} |")
A("")
A("**Attribution established rather than asserted.** UVXY is carried by")
A(f"{int(fl(ja,'attribution_test','uvxy_sleeves','weight'))} sleeves during the span,")
A(f"being {g(ja,'attribution_test','uvxy_sleeves','note')}, and")
A(f"{int(fl(ja,'attribution_test','sleeves_with_negative_contribution','weight'))} sleeves")
A(f"lose, being {g(ja,'attribution_test','sleeves_with_negative_contribution','note')}. Both")
A("conditions hold together. The worst single instrument is UVXY at")
A(f"{float([r['contribution'] for r in ja if r['table']=='instrument_attribution' and r['item']=='UVXY'][0]):+.4f}.")
A("S2 and S3 both contribute positively, so the loss is not portfolio-wide.")
A("")
A("### The event is not singular")
A("")
A(f"**{int(fl(ja,'drawdown_scan','n_windows_below_threshold','weight'))} overlapping")
A(f"fourteen-session windows across the primary window fall below")
A(f"{fl(ja,'drawdown_scan','threshold','contribution'):.2f}, and January 2013 ranks")
A(f"{int(fl(ja,'drawdown_scan','january_2013_rank','weight'))} among them.** The worst is")
A(f"{[r['date'] for r in ja if r['table']=='drawdown_window'][0]} to")
A(f"{[r['item'] for r in ja if r['table']=='drawdown_window'][0]} at")
A(f"{float([r['contribution'] for r in ja if r['table']=='drawdown_window'][0]):.6f}. The")
A("premise that the event appears in no session report because it is exceptional does")
A("not hold; it is unexceptional among this strategy's fourteen-session drawdowns.")
A("")
A("### The tie to the strata and to the strip")
A("")
A(f"Overbought tier one carries {g(ja,'strata_tie','overbought_t1_pbo_range','note')}, and")
A(f"the canonical value on that axis carries a stratum PBO of")
A(f"{fl(ja,'strata_tie','canonical_stratum_pbo','contribution'):.6f}. The same axis")
A("controls the tier-one terminal that returns UVXY at full sleeve weight.")
A("")
A("Arms starting after the span exclude the event and arms starting before include it.")
A("")
A("| arm | start | annualised | event |")
A("|---|---|---|---|")
for r in ja:
    if r["table"]=="strip_consequence":
        A(f"| {r['item']} | {r['date']} | {float(r['contribution']):.4f} | {r['note']} |")
A("")
A(f"**The strip's asymmetry.** {g(ja,'strip_asymmetry','strategy','note')}, while")
A(f"{g(ja,'strip_asymmetry','benchmarks_reinitialised','note')}.")
A(f"{int(fl(ja,'strip_asymmetry','lines_carrying_state','weight'))} of the eleven")
A("benchmark lines carry state and are therefore affected by re-entry rather than only")
A(f"repriced, being {g(ja,'strip_asymmetry','lines_carrying_state','note')}. The other")
A(f"{int(fl(ja,'strip_asymmetry','lines_entry_only','weight'))} are buy-and-hold or")
A("daily-constant and move only their entry price.")
A("")
A("## G, skipped on the budget gate")
A("")
A(f"Free memory stands at {fl(gn,'machine','free_gib'):.2f} GiB genuinely unused with")
A(f"{fl(gn,'machine','available_gib'):.2f} GiB available including inactive, against")
A(f"{fl(gn,'machine','compressor_gib'):.2f} GiB held by the compressor and")
A(f"{fl(gn,'machine','swap_free_mb'):.2f} MB of free swap.")
A("")
A(f"The corrected null needs about {fl(gn,'requirement','total_estimate_gb'):.3f} GB")
A("before Python and BLAS overhead, being the moment array, a per-specification residual")
A("array, a permutation index, and six chunk-sized arrays. **The gate fails on the RAM")
A("condition and the phase is skipped rather than run partially.** The precedent is")
A("direct, since phase B1's strictly lighter pass, without the residual and permutation")
A("arrays, already fell to 0.0 percent CPU and was killed at this machine state.")
A("")
A("The construction is recorded in `degradation-null-corrected.csv` so a later session")
A("can run it unchanged.")
A("")
A("## Findings and the class of change each would need")
A("")
A("| finding | class |")
A("|---|---|")
A("| nine of twelve ladder rows change rank across the Lo q sweep | register decision on whether 8.2 keeps the Lo-corrected Sharpe as headline |")
A("| nine of twelve rows' Lo factors are inside their own no-autocorrelation null | register decision, same 8.2 question |")
A("| N corrected to 121,500 for the deflated Sharpe | correctness repair, applied |")
A("| the effective count is 3 to 17 rather than 121,500 | post-hoc sensitivity under 9.10, primary unchanged |")
A("| config.SIZING_MODE is unwired from the engine | correctness repair to wire it, specification change to vary it |")
A("| the completion rule has no alternative arm | specification change |")
A("| the January 2013 event ranks 42nd of 69 comparable windows | documentation |")
A("| the strip compares a nested strategy against seven stateful re-initialised benchmarks | correctness repair |")
A("| the degradation slope has no valid null | register decision on removal |")
A("")
A("No recommendation is made on any of these.")
A("")
A("## Stop")
A("")
A("Phases D through F complete, phase G skipped on the budget gate. Phase C recorded as")
A("failed. Holdout untouched, grid not re-executed, no grid point adopted, no canonical")
A("value changed.")
A("")
(OUT/"REPORT-DG.md").write_text("\n".join(L)+"\n")
print(f"wrote {OUT/'REPORT-DG.md'}")
