from __future__ import annotations
import csv
from pathlib import Path
ROOT = Path("/Users/GualyCr/Downloads/tactical-allocation")
OUT = ROOT / "outputs" / "session-20"


def rd(n):
    return list(csv.DictReader(open(OUT / n)))


hu, uh, qo, cd = rd("held-universe.csv"), rd("unlisted-holdings.csv"), rd("qqq-overlap.csv"), rd("coverage-derived.csv")
cs, vs, hl = rd("chunk-scalar-sweep.csv"), rd("vacuous-check-sweep.csv"), rd("hardcoded-literal-sweep.csv")
pr, bd = rd("pbo-regression-corrected.csv"), rd("boundary-repair-delta.csv")
sr = rd("session-resources.csv")


def g(rows, t, i, f="value", key="item"):
    for r in rows:
        if r["table"] == t and r.get(key) == i:
            return r.get(f)
    return ""


def fl(rows, t, i, f="value", key="item"):
    v = g(rows, t, i, f, key)
    return float(v) if v not in ("", None) else float("nan")


def d_(t, i, f):
    for r in bd:
        if r["table"] == t and r["item"] == i:
            return r[f]
    return ""


L = []
A = L.append
A("# Session 20 report")
A("")
A("Consolidated repair, audit, and search-space accounting. Phases A through C ran,")
A("phase C's gate tripped, and phases D through G were not reached. Partial completion")
A("through a completed phase is the state this session ends in. The 2021-08-01 holdout")
A("boundary is untouched, no grid was re-executed, and no grid point was adopted or")
A("promoted. Session 15 and session 14 outputs are preserved alongside their rebuilds.")
A("")
A("Every figure below is read from an emitted CSV in `outputs/session-20/`.")
A("")
A("## SVIX and UVIX, resolved")
A("")
A(f"Both are held in code and load on neither panel. The availability switch at")
A(f"`src/sleeves.py` resolves them away, since `State.available` at")
A(f"`scripts/s13_backtest.py:344` reads `self.sig.avail.get(t)` and returns False for a")
A("ticker absent from the panel. Across the primary window the two terminals that could")
A(f"select them fired {int(fl(uh,'terminal_firing','t10_vol_short_terminal')):,} times for")
A(f"T10 and {int(fl(uh,'terminal_firing','s3_vol_terminal')):,} times for S3, while SVIX")
A(f"was selected {int(fl(uh,'terminal_firing','t10_resolved_SVIX'))} times and UVIX")
A(f"{int(fl(uh,'terminal_firing','s3_resolved_UVIX'))} times.")
A("")
A("**What the engine does with an unlisted held ticker is raise.** The fill path at")
A("`scripts/s13_backtest.py:500` reads `px = raw[t][i]` where `raw` is built only over")
A("`panel.frames`, so an absent ticker raises KeyError rather than being silently")
A("dropped, renormalised across survivors, or routed to cash. Register 1.9 covers")
A("threshold reads and is silent on weight dictionaries, and the traced behaviour is an")
A("exception.")
A("")
A(f"**Gate A2 does not trip.** The gate halts the session only if the engine raises AND")
A("the terminal can fire inside the holdout. It cannot, because the availability switch")
A("cannot select a ticker the loader excludes, so the branch is unreachable rather than")
A("merely unfired.")
A("")
A("The consequence stands regardless. SVIX and UVIX list 2022-03-30 on the frozen")
A("files, inside the holdout span beginning 2021-08-01, and the source strategy's")
A("SVIX_LIVE and UVIX_LIVE guards would activate there while this implementation will")
A("not. **The branch executed zero times in sample and will execute zero times at the")
A("holdout read under the current loader.** A session that adds the two tickers to")
A("`bt.LEVERED` activates them for the first time inside the holdout.")
A("")
A("## The canonical positive control, before and after")
A("")
A(f"Before the boundary repair, run at the top of phase A from the 339 frozen inputs,")
A(f"the canonical returned {fl(uh,'positive_control','ann_return'):.6f} annualised and")
A(f"{fl(uh,'positive_control','sharpe_lo'):.6f} Lo-corrected Sharpe over")
A(f"{int(fl(uh,'positive_control','n_sessions'))} sessions, inside a")
A(f"{fl(uh,'positive_control','tolerance'):.0e} tolerance stated before comparing.")
A("")
A(f"After the repair, the rebuilt session 14 ladder reproduces")
A(f"{float(d_('gate_C','canonical_positive_control','new')):.6f} against the pre-repair")
A(f"{float(d_('gate_C','canonical_positive_control','old')):.6f}, which is register")
A("7.14a's corrected value. The control passes on both sides.")
A("")
A("## The boundary delta")
A("")
A(f"`scripts/s14_common.py` line 29 read 2011-10-03 and no session 15 script overrode")
A(f"it, so every session 15 primary-window row carried")
A(f"{int(float(d_('scope','n_sessions_before','old')))} sessions against the corrected")
A(f"{int(float(d_('scope','n_sessions_before','new')))}.")
A("")
A("| quantity | before | after |")
A("|---|---|---|")
for m in ("ann_return", "sharpe_naive", "sharpe_lo"):
    A(f"| strategy {m} | {float(d_('strategy',m,'old')):.6f} | {float(d_('strategy',m,'new')):.6f} |")
for m, lbl in (("information_ratio", "information ratio"),
               ("tracking_error_ann", "tracking error"),
               ("alpha_t_newey_west", "Newey-West alpha t"),
               ("alpha_ann", "annualised alpha")):
    A(f"| buy-and-hold QQQ {lbl} | {float(d_('relative_metric','buy_hold_QQQ.'+m,'old')):.6f} | "
      f"{float(d_('relative_metric','buy_hold_QQQ.'+m,'new')):.6f} |")
A("")
A("All twelve ladder rows on the Lo-corrected Sharpe.")
A("")
A("| line | before | after | rank before | rank after |")
A("|---|---|---|---|---|")
for r in bd:
    if r["table"] == "ladder_row" and r["metric"] == "sharpe_lo":
        A(f"| {r['item']} | {float(r['old']):.4f} | {float(r['new']):.4f} | "
          f"{r['rank_old']} | {r['rank_new']} |")
A("")
A("**No rank changes.** The strategy holds sixth of twelve on both metrics.")
A("")
A("## Gate C, tripped")
A("")
A("The gate halts the session before phase D if the rebuilt canonical fails its control")
A("or if either randomization null ceases to clear p below 0.001 on the designated cell.")
A("The control passes. The nulls do not both clear.")
A("")
A("| null | metric | p before | p after | clears p below 0.001 |")
A("|---|---|---|---|---|")
for r in bd:
    if r["table"] == "gate_C" and "|" in r["item"]:
        nl, lab = r["item"].split("|")
        A(f"| {nl} | {lab} | {float(r['old']):.3f} | {float(r['new']):.3f} | "
          f"{'yes' if 'DOES NOT' not in r['metric'] else 'no'} |")
A("")
A("The timing-shuffle null on annualised return moves from p 0.000 to p 0.001, and the")
A("strategy's percentile on that arm moves from 100.0 to")
A(f"{float(d_('null','o2o|primary|timing_shuffle_block_bootstrap|strategy_percentile_ann','new')):.1f}.")
A("On the Lo-corrected Sharpe, which 8.2 designates as headline, both nulls remain at p")
A("0.000 with the strategy at the 100th percentile. The session halts here as")
A("instructed rather than absorbing the change.")
A("")
A("Romano-Wolf across eleven comparisons keeps one below 0.05, the equal-weight")
A(f"universe moving from {float(d_('romano_wolf','strategy_minus_equal_weight_universe','old')):.3f}")
A(f"to {float(d_('romano_wolf','strategy_minus_equal_weight_universe','new')):.3f} with the")
A("strategy above. Buy-and-hold QQQ moves from")
A(f"{float(d_('romano_wolf','strategy_minus_buy_hold_QQQ','old')):.3f} to")
A(f"{float(d_('romano_wolf','strategy_minus_buy_hold_QQQ','new')):.3f}.")
A("")
A("## Phase A, the derived universe")
A("")
A(f"Derived from the AST of `src/sleeves.py` with no list written by hand,")
A(f"**{int(fl(hu,'counts','n_held','line','ticker'))} held** and")
A(f"**{int(fl(hu,'counts','n_signal_only','line','ticker'))} signal-only**, which")
A("reconciles exactly with session 19.6. `outputs/session-20/held-universe.csv` carries")
A("the sleeve, terminal, line number, and weight expression for every held ticker and")
A("supersedes every hardcoded list in the repository.")
A("")
A(f"QQQ is held rather than a signal input, on")
A(f"{int(fl(qo,'holding','sessions_holding_qqq')):,} of")
A(f"{int(fl(qo,'holding','sessions_in_window')):,} sessions at a mean conditional weight")
A(f"of {fl(qo,'holding','mean_weight_conditional'):.4f} and a mean unconditional weight")
A(f"of {fl(qo,'holding','mean_weight_unconditional'):.4f}. The arithmetic share of the")
A(f"strategy's summed daily return attributable to that position is")
A(f"{fl(qo,'overlap','share_of_arithmetic_return'):.6f}, so the gap against buy-and-hold")
A("QQQ is partly a comparison of the strategy against a component of itself.")
A("")
A("Coverage recomputed on the derived set gives")
A(f"{int(fl(cd,'coverage','realized_sessions_any_held_unlisted')):,} realized-panel")
A(f"sessions and {int(fl(cd,'coverage','synthetic_sessions_any_held_unlisted'))} synthetic-panel")
A("sessions carrying a held ticker unlisted, against")
A(f"{fl(cd,'distinction','unavailable_fills_from_2011_10_04'):.1f} unavailable fills in")
A("`outputs/session-16/boundary-correction.csv`. The two are different quantities and")
A("are named separately here. Strict full composition is unreachable on any date, since")
A("SVIX and UVIX load on neither panel.")
A("")
A("## Phase B, three class sweeps")
A("")
A("**B1, the chunk-first-element class.** The sweep found the shape at four files")
A("rather than the two the scaffold named, being `s19_step4.py`, `s18_step3.py`,")
A("`s19_draws.py`, and `s19_step5.py`, the last of which is the stratified pass. All")
A("four are repaired to a per-combination count. Two further hits in")
A("`s13_5_diagnostics.py` are tuple indexing and are recorded as false positives.")
A("")
A("**The re-emission halted on the memory gate.** Free plus inactive memory stood at")
A(f"{fl(pr,'machine_state','free_plus_inactive_gib'):.2f} GiB with the ceiling stated at")
A(f"{fl(pr,'machine_state','memory_ceiling_gb'):.2f} GB and the chunk at")
A(f"{int(fl(pr,'machine_state','chunk'))} against session 19's 514. The pass fell to zero")
A("percent CPU with 400 KB resident and was killed rather than allowed to continue into")
A(f"swap, with free swap down to {fl(pr,'halt','free_swap_at_kill_mb'):.2f} MB. No")
A("regression figure was re-emitted. The known magnitude of the outstanding shift is")
A(f"{g(pr,'outstanding','known_magnitude')} on the S equal to 16 slope, measured by")
A("session 19.6 at chunk 514.")
A("")
A("PBO and the stratified PBO are immune and were not re-run. Within a chunk the")
A("substituted count is one scalar applied to every specification, so it scales every")
A("Sharpe identically and preserves the ordering the rank and the argmax read, and PBO")
A("is a function of that ordering alone. Session 19.6 measured a PBO gap of exactly")
A("0.0e+00 at chunk 128, 257, and 514, which is the empirical half of the same argument.")
A("")
A("**B2, the vacuous-check class.** Five checks are repaired with an explicit")
A("cardinality floor asserted before the predicate.")
A("")
A("| check | floor | basis |")
A("|---|---|---|")
for r in vs:
    if r["table"] == "check" and r.get("floor"):
        A(f"| {r['item']} | {r['floor']} | {r['basis']} |")
A("")
A("**B3, the hardcoded literal class.** The sweep covers")
A(f"{len([r for r in hl if r['table']=='literal'])} numeric literal sites and")
A(f"{len([r for r in hl if r['table']=='ticker_list'])} ticker-list sites, of which")
A(f"{len([r for r in hl if r.get('diverged')=='1'])} diverge from their authoritative")
A("source. Divergent ticker lists are reported against the derived held set rather than")
A("repaired wholesale, since replacing every list is a specification change rather than")
A("a correctness repair, and the single divergence that entered an emitted measurement")
A("was `s195_strip.py`, already superseded by the phase A artifact.")
A("")
A("## Phases not reached")
A("")
A("| phase | status | reason |")
A("|---|---|---|")
A("| B1 re-emission | halted | memory gate, machine in swap |")
A("| C, s15_step12 rebuild | not run | session ended at the gate C halt |")
A("| D, metric audit | not reached | gate C halts before phase D |")
A("| E, search-space accounting | not reached | gate C halts before phase D |")
A("| F, January 2013 event | not reached | gate C halts before phase D |")
A("| G, corrected degradation null | not reached | gate C, and the budget gate would have failed independently on the memory state |")
A("")
A("## Findings and the class of change each would need")
A("")
A("| finding | class |")
A("|---|---|")
A("| the primary window boundary was superseded in every session 15 output | correctness repair, applied |")
A("| the chunk-first-element count at four sites | correctness repair, code applied and re-emission outstanding |")
A("| five checks passing on empty input | correctness repair, applied |")
A("| the timing-shuffle null on annualised return no longer clears p below 0.001 | register decision on what the paper claims |")
A("| SVIX and UVIX are unreachable in sample and at the holdout read | register decision on whether the loader should carry them |")
A("| QQQ is held and also a ladder benchmark | documentation |")
A("| divergent hardcoded ticker lists across the repository | specification change to refactor, documentation as diagnosed |")
A(f"| the matched-exposure row was built at the registered exposure where D25 gives "
  f"{[r['value'] for r in sr if r['metric']=='exposure' and '1.777' in r['item']][0]} | correctness repair, rebuilt |")
A("")
A("No recommendation is made on any of these.")
A("")
A("## Machine state and resources")
A("")
A(f"Measured before any moment-array load. Free plus inactive")
A(f"{fl(pr,'machine_state','free_plus_inactive_gib'):.2f} GiB on an 8 GiB machine, with")
A(f"swap reading {g(pr,'machine_state','swap','note')}. The derived ceiling was")
A(f"{fl(pr,'machine_state','memory_ceiling_gb'):.2f} GB.")
A("")
A("| phase | peak resident | wall clock |")
A("|---|---|---|")
A(f"| A | {g(sr,'phase','A','value')} GB | {g(sr,'phase','A','value','metric') and ''}"
  f"{[r['value'] for r in sr if r['table']=='phase' and r['item']=='A' and r['metric']=='seconds'][0]} s |")
A(f"| B sweeps | under {[r['value'] for r in sr if r['item']=='B_sweeps'][0]} GB | seconds |")
A("| B1 re-emission | halted | killed on the memory gate |")
A("| C rebuilds | single-specification engine runs | several minutes per script |")
A("")
A("## What remains open before the holdout can run")
A("")
A("- **Gate C is unresolved.** The timing-shuffle null on annualised return sits at p")
A("  0.001 rather than below it, and what the paper claims from that is a register")
A("  decision this session does not make.")
A("- **The B1 re-emission is outstanding**, so the three regression figures in")
A("  `outputs/session-19/pbo.csv` and the regression columns of `pbo-strata.csv` still")
A("  carry the chunk-dependent count.")
A("- **Phases D through G are unrun**, so the Lo q sweep, the deflated Sharpe")
A("  correction to N equal to 121,500, the axis census, the three unsourced 9.11 axes,")
A("  effective N, the January 2013 attribution, and the corrected degradation null all")
A("  remain open.")
A("- **A2 leaves one code path untested at the holdout read.** The SVIX and UVIX")
A("  branches will not execute inside the holdout under the current loader, so the")
A("  holdout measures a strategy that differs from the source over the span from")
A("  2022-03-30.")
A("- **D16**, the financing spread, remains assumed.")
A("")
A("## Stop")
A("")
A("Halted after phase H with gate C tripped. No holdout executed, no grid re-executed,")
A("no grid point adopted, no canonical value changed on any axis, and the primary window")
A("remains 2011-10-04. One commit.")
A("")
(OUT / "REPORT.md").write_text("\n".join(L) + "\n")
print(f"wrote {OUT/'REPORT.md'}")
