from __future__ import annotations
import csv, subprocess, re
from pathlib import Path
ROOT=Path("/Users/GualyCr/Downloads/tactical-allocation"); OUT=ROOT/"outputs/session-21"
def rd(n): return list(csv.DictReader(open(OUT/n)))
sres = rd("session-resources.csv")
uc,cp,sr,bd,rc,rr = (rd("unwired-config.csv"),rd("canonical-provenance.csv"),
  rd("subsample-representativeness.csv"),rd("beta-decomposition.csv"),
  rd("recentred-comparison.csv"),rd("reads.csv"))
def g(rs,t,i,f="value",key="item"):
    for r in rs:
        if r["table"]==t and r.get(key)==i: return r.get(f)
    return ""
def fl(rs,t,i,f="value",key="item"):
    v=g(rs,t,i,f,key); return float(v) if v not in ("",None) else float("nan")
L=[];A=L.append
A("# Session 21 report")
A("")
A("Provenance, representativeness, and the beta decomposition. Phases A through F all")
A("ran, gate A and gate C both cleared, and no phase was skipped. The 2021-08-01 holdout")
A("boundary is untouched, no grid was re-executed, no grid point was adopted, and")
A("nothing phase A diagnoses was repaired.")
A("")
A("**The machine has not been rebooted since session 20.** Uptime is fourteen days from")
A("a 2026-08-06 boot, so every ceiling below derives from current state rather than from")
A(f"session 19's {[r['value'] for r in sres if r['item']=='session19_peak_rss_gb'][0]} GB "
  f"figure. No phase in this session loads the moment array, and")
A("the heaviest load is the 70 MB metric shard set.")
A("")
A("Every figure below is read from an emitted CSV in `outputs/session-21/`.")
A("")
A("## The three openers")
A("")
_nparam=len([r for r in uc if r["table"]=="parameter"])
_nnone=len([r for r in uc if r["table"]=="parameter"
            and r["classification"] in ("none","validate_only")])
_ndead=len([r for r in uc if r["table"]=="dead_read"])
A(f"**The unwired-config verdict.** Of {_nparam} parameters defined in `src/config.py`,")
A(f"{_nnone} have no consumer outside config.py and {_ndead} more carry a read that is")
A("never invoked.")
A("**Gate A clears**, since all nine grid axis attributes are read by the engine, so")
A("the 121,500 count stands.")
A("")
A(f"**The canonical provenance verdict.** Eight of the nine axes carry a value fixed")
A(f"before any comparison on that axis. One does not. `crash_threshold` at")
A(f"{g(cp,'axis','crash_threshold','canonical_value','axis')} moved from the source value")
A("of minus 12 to minus 10 at session 04 and to its present value at session 09, after")
A("measurements at sessions 03 and 06, and the register marks it a stipulation. The")
A("percentile claim is supported on eight axes and weakened on one.")
A("")
A(f"**The beta decomposition's residual Sharpe.** Hedging out QQQ beta leaves a residual")
A(f"stream at a naive Sharpe of **{fl(bd,'static','residual_sharpe_naive'):.6f}** and a")
A(f"Lo-corrected Sharpe of **{fl(bd,'static','residual_sharpe_lo'):.6f}**, against the")
A("strategy's own 1.0911 and 1.3817.")
A("")
A("## Phase A, the unwired-config sweep")
A("")
A("A read is detected on the abstract syntax tree rather than by regex, since docstring")
A("prose naming a parameter is not a read, and dynamic `getattr(config, ...)` resolution")
A("is detected separately, since no attribute walk sees it.")
A("")
A("| classification | count |")
A("|---|---|")
for cls in ("engine","harness","validate_only","none"):
    n=len([r for r in uc if r["table"]=="parameter" and r["classification"]==cls])
    A(f"| {cls} | {n} |")
A("")
A(f"The {_nnone} with no consumer.")
A("")
A("| parameter | classification |")
A("|---|---|")
for r in uc:
    if r["table"]=="parameter" and r["classification"] in ("none","validate_only"):
        A(f"| {r['param']} | {r['classification']} |")
A("")
A("**Two parameters carry a read that is never invoked.** `SIZING_MODE` and")
A("`EXECUTION_MODE` are read by `src/execution.py` as default arguments of")
A("`size_position`, and no module in the return-generating path calls `size_position`.")
A("The engine hardcodes `math.trunc` at `scripts/s13_backtest.py:528`, so both have a")
A("read site and no influence on any result.")
A("")
A(f"**`FINANCING_SPREAD_BP` is read by the harness and not by the engine.** Its readers")
A(f"are the synthetics builder and validator plus session scripts, so the financing")
A("spread enters results only through the pre-built reconstructions on the synthetic")
A("arm. On the realized arm, which is the designated cell, no financing model applies at")
A("all, since the levered funds carry the issuer's own financing inside their price")
A("history. D16 records the spread as assumed and treated by the cost sweep, and this")
A("establishes that the engine never reads it.")
A("")
A("**The completion rule is not a config parameter.** It is hardcoded in the fill path")
A("and `scripts/s13_backtest.py` lines 18 to 24 mark it provisional and not a register")
A("closure, so it is unregistered rather than unread.")
A("")
A(f"**One unread parameter sits on the specification curve.** `SLIPPAGE_MODEL` and")
A(f"`SLIPPAGE_MODELS` have no consumer, while `slippage_model` is a curve axis in")
A("`outputs/session-19/specification-curve.csv`. The axis was varied through function")
A("selection in the cost sweep rather than through the config value, so the curve is")
A("real and the config parameter is inert. No grid axis is affected, which is why gate A")
A("clears.")
A("")
A("## Phase B, canonical axis provenance")
A("")
A("| axis | canonical | register | state |")
A("|---|---|---|---|")
for r in cp:
    if r["table"]=="axis":
        A(f"| {r['axis']} | {r['canonical_value']} | {r['register_item']} | {r['state']} |")
A("")
A(f"{g(cp,'verdict','percentile_claim_support','note','axis')}")
A("")
A(f"**A documentation caveat travels with it.** {g(cp,'caveat','dating','note','axis')}")
A("")
A("## Phase C, subsample representativeness")
A("")
A("| quantity | subsample | full grid |")
A("|---|---|---|")
for nm in ("mean","sd","p05","p50","p95"):
    A(f"| naive Sharpe {nm} | {fl(sr,'distribution',f'sharpe_naive_subsample_{nm}'):.6f} | "
      f"{fl(sr,'distribution',f'sharpe_naive_full_grid_{nm}'):.6f} |")
A("")
A(f"The primary test is a resampling null of {int(fl(sr,'resampling_null','draws'))} random")
A(f"subsets at seed {int(fl(sr,'resampling_null','seed'))} fixed before drawing, which makes")
A("no distributional assumption and respects the finite population exactly. The observed")
A(f"subsample mean of {fl(sr,'resampling_null','observed_subsample_mean'):.6f} sits at the")
A(f"{fl(sr,'resampling_null','observed_percentile'):.2f} percentile of that null, a")
A(f"two-sided p of {fl(sr,'resampling_null','two_sided_p'):.4f}.")
A("")
A(f"The Kolmogorov-Smirnov distance is {fl(sr,'ks','statistic'):.6f} and is reported as a")
A("distance rather than a test, since both of its assumptions fail here.")
A("")
A(f"Axis balance holds at {int(fl(sr,'axis_balance_summary','values_balanced'))} of")
A(f"{int(fl(sr,'axis_balance_summary','values_balanced','target'))} axis values inside a 99")
A("percent binomial interval, and the canonical is present.")
A("")
A(f"**Gate C clears.** {g(sr,'licence','what_this_licenses','note')}")
A("")
A("## Phase D, the beta decomposition")
A("")
A(f"The positive control passes, with the benchmark regressed on itself returning beta")
A(f"{fl(bd,'positive_control','beta'):.6f} and an alpha whose absolute value is below")
A(f"the tolerance, inside a")
A(f"{fl(bd,'positive_control','tolerance'):.0e} tolerance stated before comparing.")
A("")
A("### Static")
A("")
A("| quantity | value |")
A("|---|---|")
for k,lbl in (("beta","beta"),("alpha_annualised","alpha annualised"),
              ("r_squared","R-squared"),("alpha_t_newey_west","Newey-West alpha t"),
              ("residual_ann_return","hedged residual annualised return"),
              ("residual_ann_vol","hedged residual annualised volatility"),
              ("residual_sharpe_naive","hedged residual naive Sharpe"),
              ("residual_sharpe_lo","hedged residual Lo-corrected Sharpe")):
    A(f"| {lbl} | {fl(bd,'static',k):.6f} |")
A("")
A(f"{g(bd,'static','residual_definition','note')}.")
A("")
A(f"The Newey-West lag is {int(fl(bd,'setup','newey_west_lag'))}, which 8.11 fixes before")
A("the run for every alpha t-statistic in this project rather than being chosen here.")
A("")
A("### Rolling")
A("")
A(f"The window is {int(fl(bd,'rolling','window'))} sessions, read from")
A("`config.CRASH_HORIZON_SESSIONS`, the only rolling lookback the register records for a")
A("return-based estimator.")
A("")
A("| quantity | value |")
A("|---|---|")
for k,lbl in (("beta_mean","mean"),("beta_sd","standard deviation"),
              ("beta_min","minimum"),("beta_max","maximum"),
              ("share_beta_above_1.0","share of sessions above 1.0"),
              ("share_beta_above_1.7","share of sessions above 1.7")):
    A(f"| rolling beta {lbl} | {fl(bd,'rolling',k):.6f} |")
A("")
A("### Timing against selection")
A("")
A(f"Excess return decomposes as a static exposure component, a timing component, and a")
A(f"residual, with the rolling beta lagged one session so no session uses its own data.")
A("")
A("| component | annualised contribution | naive Sharpe | Lo Sharpe |")
A("|---|---|---|---|")
for k,lbl in (("static_exposure","static exposure"),("timing","timing"),
              ("residual","residual")):
    A(f"| {lbl} | {fl(bd,'timing_decomposition',k+'_ann_contribution'):+.6f} | "
      f"{fl(bd,'timing_decomposition',k+'_sharpe_naive'):.6f} | "
      f"{fl(bd,'timing_decomposition',k+'_sharpe_lo'):.6f} |")
A(f"| total | {fl(bd,'timing_decomposition','total_ann_check'):+.6f} | | |")
A("")
A("**Timing contributes the smallest of the three components.** The residual is the")
A("largest and the static exposure component is between them.")
A("")
A("### The exposure-matched null")
A("")
A(f"{g(bd,'exposure_matched','construction','note')}.")
A("")
A("| quantity | value |")
A("|---|---|")
for k,lbl in (("ann_return","annualised return"),("ann_vol","annualised volatility"),
              ("sharpe_naive","naive Sharpe"),("sharpe_lo","Lo-corrected Sharpe"),
              ("ann_turnover","annualised turnover")):
    A(f"| {lbl} | {fl(bd,'exposure_matched',k):.6f} |")
A(f"| ladder position on naive Sharpe | {int(fl(bd,'exposure_matched','ladder_rank_sharpe_naive'))} of thirteen |")
A(f"| ladder position on Lo-corrected Sharpe | {int(fl(bd,'exposure_matched','ladder_rank_sharpe_lo'))} of thirteen |")
A("")
A(f"The exposure-matched line reaches a naive Sharpe of")
A(f"{fl(bd,'exposure_matched','sharpe_naive'):.6f} against the strategy's 1.0911 and a")
A(f"Lo-corrected Sharpe of {fl(bd,'exposure_matched','sharpe_lo'):.6f} against 1.3817.")
A("Reported as measured, with no characterisation.")
A("")
A("## Phase E, the recentred comparison")
A("")
A(f"{g(rc,'grounds','deflated_sharpe_removed','note')}")
A("")
A("| point | naive Sharpe | z from grid mean | percentile | rank |")
A("|---|---|---|---|---|")
for lab in ("canonical","in_sample_best"):
    A(f"| {lab} | {fl(rc,'recentred',f'{lab}_sharpe_naive_value'):.6f} | "
      f"{fl(rc,'recentred',f'{lab}_sharpe_naive_z_from_grid_mean'):.6f} | "
      f"{fl(rc,'recentred',f'{lab}_sharpe_naive_percentile'):.2f} | "
      f"{int(fl(rc,'recentred',f'{lab}_sharpe_naive_rank'))} |")
A("")
A("Two correlation-accounting methods are reported so the choice is visible.")
A("")
A(f"**Method one.** {g(rc,'correlation_method','method_1_empirical','note')}.")
A("")
A(f"**Method two.** {g(rc,'correlation_method','method_2_effective_count','note')}.")
A("")
A("| effective count | value | expected maximum z | canonical exceeds |")
A("|---|---|---|---|")
for nm in ("participation_ratio","spectral_entropy","variance_threshold_95","nominal_121500"):
    A(f"| {nm} | {fl(rc,'expected_max',nm+'_effective_count'):.2f} | "
      f"{fl(rc,'expected_max',nm+'_expected_max_z'):.4f} | "
      f"{'yes' if g(rc,'expected_max',nm+'_canonical_exceeds')=='1' else 'no'} |")
A("")
A("The canonical exceeds the expected maximum only at the participation-ratio count and")
A("not at the other three. The two methods disagree, which is the point of reporting")
A("both rather than one.")
A("")
A("## Phase F, reads and confirmations")
A("")
A(f"**F1, cost crossings.** The sweep spans {g(rr,'F1','sweep_range_bp','note')} bp across")
A(f"{int(fl(rr,'F1','sweep_range_bp'))} points. Crossings against each of the eleven")
A("benchmark lines under both conventions are in `reads.csv`, each marked as inside the")
A("swept range or as an extrapolation.")
A("")
A(f"**F2, leave-one-out provenance.** {g(rr,'F2','files','note')}. These were **not**")
A("rebuilt by session 20 phase C, which covered `s14_ladder`, `s14_nulls`, `s15_metrics`")
A(f"and `s15_rest` only, so they carry the superseded boundary. {g(rr,'F2','1.5636_agreement','note')}")
A("")
A(f"**F3, the 8.7 reconciliation.** {g(rr,'F3','what_each_total_now_refers_to','note')}.")
A("")
A(f"**F4, the null replication count.** {g(rr,'F4','gate_defect','note')}.")
A("")
A(f"**F5, distinct episodes.** The {int(fl(rr,'F5','overlapping_windows_below_threshold'))}")
A(f"overlapping fourteen-session windows collapse to")
A(f"**{int(fl(rr,'F5','distinct_non_overlapping_episodes'))} distinct non-overlapping")
A(f"episodes**, and January 2013 ranks")
A(f"{int(fl(rr,'F5','january_2013_rank_among_episodes'))} among them, against the 42nd of")
A("69 that session 20 reported on the overlapping count.")
A("")
A("## Findings and the class of change each would need")
A("")
A("| finding | class |")
A("|---|---|")
A("| ten config parameters have no consumer | documentation, or a correctness repair to remove them |")
A("| SIZING_MODE and EXECUTION_MODE are read but never invoked | correctness repair to wire, specification change to vary |")
A("| FINANCING_SPREAD_BP is never read by the engine | documentation, and it bears on how D16 is described |")
A("| SLIPPAGE_MODEL is inert while slippage_model is a curve axis | documentation |")
A("| crash_threshold was fixed after measurement on its own axis | register decision on how the percentile claim is stated |")
A("| the subsample is representative | documentation, and it licenses phase E |")
A("| the beta-hedged residual Sharpe is below the headline | documentation |")
A("| the exposure-matched line reaches a higher naive Sharpe than the strategy | register decision on what the ladder claims |")
A("| the deflated Sharpe rests on a misspecified null | correctness repair, applied by removal |")
A("| the two correlation-accounting methods disagree | register decision on which is reported |")
A("| the session 20 gate turns on a single draw at 1,000 replications | specification change to raise the replication count |")
A("")
A("No recommendation is made on any of these.")
A("")
A("## What remains open before the holdout can run")
A("")
A("- **The session 20 gate C outcome is unresolved**, since clearing p below 0.001 at")
A("  1,000 draws requires zero exceedances and turns on a single draw.")
A("- **The session 20 B1 re-emission and phase G are still outstanding**, both halted on")
A("  memory, and the machine has not been rebooted since.")
A("- **The Lo q remains unregistered**, and the 8.2 question of whether the Lo-corrected")
A("  Sharpe stays headline is open.")
A("- **The leave-one-out artifacts carry the superseded boundary.**")
A("- **SVIX and UVIX leave a code path that will not execute at the holdout read.**")
A("- **D16 stands**, and phase A establishes the engine never reads the spread.")
A("")
A("## Resources")
A("")
A("| phase | peak resident | wall clock |")
A("|---|---|---|")
def _res(ph,met):
    for r in sres:
        if r["table"]=="phase" and r["item"]==ph and r["metric"]==met: return r["value"]
    return ""
for ph,lbl in (("A","A"),("B","B"),("C","C"),("D","D"),("EF","E and F")):
    pk,sc=_res(ph,"peak_rss_gb"),_res(ph,"seconds")
    A(f"| {lbl} | {pk+' GB' if pk else 'documentary, no array load'} | "
      f"{sc+' s' if sc else 'under a second'} |")
A("")
A("## Stop")
A("")
A("Halted after phase G. No holdout executed, no grid re-executed, no grid point")
A("adopted, no canonical value changed, no null re-run, and nothing phase A diagnoses")
A("was repaired.")
A("")
(OUT/"REPORT.md").write_text("\n".join(L)+"\n")
print(f"wrote {OUT/'REPORT.md'}")
