from __future__ import annotations
import csv
from pathlib import Path
OUT=Path("/Users/GualyCr/Downloads/tactical-allocation/outputs/session-23")
def rd(n): return list(csv.DictReader(open(OUT/n)))
pa,dn,rr = rd("pbo-regression-corrected.csv"),rd("degradation-null-corrected.csv"),rd("resource-record.csv")
def g(rs,t,i,f="value"):
    for r in rs:
        if r["table"]==t and r["item"]==i: return r[f]
    return ""
def fl(rs,t,i,f="value"):
    v=g(rs,t,i,f); return float(v) if v not in ("",None) else float("nan")
L=[];A=L.append
A("# Session 23 report")
A("")
A("The quiet-machine pass, on a machine that was not quiet. Phase A halted on the")
A("contention condition before launching, phase B was skipped as dependent on it, and")
A("phases C and D ran. The 2021-08-01 holdout boundary is untouched, no grid was")
A("re-executed, and no grid point was adopted.")
A("")
A("Free memory is not reported as headroom anywhere. The metrics used are load average,")
A("process CPU percent, compressor size, swap used, swap free, and page-outs.")
A("")
A("## Machine state at launch")
A("")
A("| quantity | value |")
A("|---|---|")
A(f"| cores | {int(fl(pa,'machine_at_launch','cores'))} |")
A(f"| halt threshold, twice the core count | {int(fl(pa,'machine_at_launch','halt_threshold'))} |")
A(f"| load average, one minute | {fl(pa,'machine_at_launch','load_1min')} |")
A(f"| load average, five minute | {fl(pa,'machine_at_launch','load_5min')} |")
A(f"| load average, fifteen minute | {fl(pa,'machine_at_launch','load_15min')} |")
A(f"| compressor | {fl(pa,'machine_at_launch','compressor_gib')} GiB |")
A(f"| swap used | {fl(pa,'machine_at_launch','swap_used_mb')} MB |")
A(f"| swap free | {fl(pa,'machine_at_launch','swap_free_mb')} MB |")
A("")
A("The five processes consuming the most CPU at launch.")
A("")
A("| rank | percent | process |")
A("|---|---|---|")
for i in (1,2,3,4,5):
    v=g(pa,"top_process",f"rank_{i}")
    if v: A(f"| {i} | {float(v):.1f} | {g(pa,'top_process',f'rank_{i}','note')} |")
A("")
A(f"The load average of {fl(pa,'machine_at_launch','load_1min')} is")
A(f"{fl(rr,'session_23','load_to_core_ratio'):.4f} times the")
A("core count and higher than the 39.57 session 22 recorded when its pass failed to")
A("complete. Five samples taken before this reading showed the one-minute figure between")
A(f"60 and 63 with the five and fifteen minute figures rising, and by the phase C write")
A(f"the one-minute figure read {fl(rr,'session_23','load_now')}, so the load was not a")
A("transient spike.")
A("")
A("## Phase A, the B1 re-emission")
A("")
A(f"**Halted on the contention condition without launching.** {g(pa,'result','reason','note')}.")
A("")
A("The abandonment rule was written to the artifact before the halt check, so the")
A(f"pre-registration stands unconsumed. The limit would have been")
A(f"{fl(pa,'preregistration','wall_limit_seconds'):.0f} seconds, being")
A(f"{g(pa,'preregistration','wall_limit_seconds','note')}, at chunk")
A(f"{int(fl(pa,'preregistration','chunk'))}, which {g(pa,'preregistration','chunk','note')}.")
A("")
A("The standing positive control passes, with the canonical rebuilt from the frozen")
A(f"inputs returning {fl(pa,'positive_control','ann_return'):.6f} annualised and")
A(f"{fl(pa,'positive_control','sharpe_lo'):.6f} Lo-corrected Sharpe over")
A(f"{int(fl(pa,'positive_control','n_sessions'))} sessions inside a")
A(f"{fl(pa,'positive_control','tolerance'):.0e} tolerance stated before comparing.")
A("")
A(f"{g(pa,'result','session_title_note','note')}.")
A("")
A("## Phase B, the corrected degradation null")
A("")
A(f"**Skipped.** {g(dn,'dependency','runs_only_if_phase_A_completed','note')}.")
A("")
A(f"The construction stays as recorded, being read from")
A(f"{g(dn,'construction','read_from')} and unmodified. {g(dn,'construction','read_from','note')}.")
A("")
A(f"**{g(dn,'consequence','slope_removal_stands','note')}.**")
A("")
A("## Phase C, the resource record")
A("")
A(f"The constraint is {g(rr,'diagnosis','constraint')}, {g(rr,'diagnosis','constraint','note')}.")
A("")
A("| observation from session 22 | value |")
A("|---|---|")
for k,lbl in (("peak_rss_gb","peak resident"),("max_pageouts_per_second","maximum page-out rate"),
              ("compressor_gib","compressor"),("load_average","load average"),
              ("process_cpu_mean_percent","process CPU mean percent")):
    A(f"| {lbl} | {g(rr,'evidence_22',k)} |")
A("")
A(f"**Neither pass ran this session**, so {g(rr,'session_23','passes_completed','note')}.")
A("")
A("### The diagnosis history")
A("")
A("| stage | claim | what was actually established |")
A("|---|---|---|")
for k in ("1_session_21","2_correction","3_session_22","4_session_23"):
    A(f"| {k.split('_',1)[1].replace('_',' ')} | {g(rr,'history',k)} | {g(rr,'history',k,'note')} |")
A("")
A(f"{g(rr,'class','register_corrections_produced','note')}.")
A("")
A(f"The record is kept because {g(rr,'class','lesson_recorded','note')}.")
A("")
A("## Findings and the class of change each would need")
A("")
A("| finding | class |")
A("|---|---|")
A("| the machine is under heavier contention than when session 22's pass failed | documentation |")
A("| the B1 re-emission remains outstanding, with a measured reason | correctness repair, deferred |")
A("| the corrected degradation null remains unrun | documentation, since the slope's removal did not rest on it |")
A("| the diagnosis class has produced three register corrections | documentation |")
A("")
A("No recommendation is made on any of these.")
A("")
A("## What remains open before the holdout can run")
A("")
A("**Two measurements remain outstanding**, being the B1 re-emission and the corrected")
A("degradation null. Neither is load-bearing. The chunk-first-element defect is repaired")
A("in code at four sites and the degradation slope is removed from the paper at 9.35, so")
A("both close defects rather than restore figures.")
A("")
A("- **Ten config parameters have no consumer** and two more are read but never invoked.")
A("- **`crash_threshold` was fixed after measurement on its own axis.**")
A("- **SVIX and UVIX leave a code path that will not execute at the holdout read**, with")
A("  the loader left unchanged deliberately.")
A("- **D16 and D23 stand.**")
A("")
A("## Resources per phase")
A("")
A("| phase | load one minute | compressor GiB | swap used MB | swap free MB |")
A("|---|---|---|---|---|")
A(f"| A, at the halt check | {fl(pa,'machine_at_launch','load_1min')} | "
  f"{fl(pa,'machine_at_launch','compressor_gib')} | "
  f"{fl(pa,'machine_at_launch','swap_used_mb')} | "
  f"{fl(pa,'machine_at_launch','swap_free_mb')} |")
A("| B | not launched | | | |")
A(f"| C, at the write | {fl(rr,'session_23','load_now')} | "
  f"{fl(rr,'session_23','compressor_gib')} | {fl(rr,'session_23','swap_used_mb')} | "
  f"{fl(rr,'session_23','swap_free_mb')} |")
A("")
A("No process CPU percent is reported for a measured pass, since no pass ran.")
A("")
A("## Stop")
A("")
A("Halted after phase D. No holdout executed, no grid re-executed, no grid point")
A("adopted, no canonical value changed, and the primary window remains 2011-10-04.")
A("")
(OUT/"REPORT.md").write_text("\n".join(L)+"\n")
print(f"wrote {OUT/'REPORT.md'}")
